package prijava.beans;
// Generated Jul 8, 2018 12:04:19 PM by Hibernate Tools 4.3.1



/**
 * Clanprojekat generated by hbm2java
 */
public class Clanprojekat  implements java.io.Serializable {


     private ClanprojekatId id;
     private Clan clan;
     private Projekat projekat;
     private String ulogauprojektu;

    public Clanprojekat() {
    }

    public Clanprojekat(ClanprojekatId id, Clan clan, Projekat projekat, String ulogauprojektu) {
       this.id = id;
       this.clan = clan;
       this.projekat = projekat;
       this.ulogauprojektu = ulogauprojektu;
    }
   
    public ClanprojekatId getId() {
        return this.id;
    }
    
    public void setId(ClanprojekatId id) {
        this.id = id;
    }
    public Clan getClan() {
        return this.clan;
    }
    
    public void setClan(Clan clan) {
        this.clan = clan;
    }
    public Projekat getProjekat() {
        return this.projekat;
    }
    
    public void setProjekat(Projekat projekat) {
        this.projekat = projekat;
    }
    public String getUlogauprojektu() {
        return this.ulogauprojektu;
    }
    
    public void setUlogauprojektu(String ulogauprojektu) {
        this.ulogauprojektu = ulogauprojektu;
    }




}


