package prijava.beans;
// Generated Feb 13, 2018 3:26:51 PM by Hibernate Tools 4.3.1



/**
 * ClanprojekatId generated by hbm2java
 */
public class ClanprojekatId  implements java.io.Serializable {


     private int idclan;
     private int idprojekat;

    public ClanprojekatId() {
    }

    public ClanprojekatId(int idclan, int idprojekat) {
       this.idclan = idclan;
       this.idprojekat = idprojekat;
    }
   
    public int getIdclan() {
        return this.idclan;
    }
    
    public void setIdclan(int idclan) {
        this.idclan = idclan;
    }
    public int getIdprojekat() {
        return this.idprojekat;
    }
    
    public void setIdprojekat(int idprojekat) {
        this.idprojekat = idprojekat;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClanprojekatId) ) return false;
		 ClanprojekatId castOther = ( ClanprojekatId ) other; 
         
		 return (this.getIdclan()==castOther.getIdclan())
 && (this.getIdprojekat()==castOther.getIdprojekat());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdclan();
         result = 37 * result + this.getIdprojekat();
         return result;
   }   


}


