package prijava.beans;
// Generated Feb 13, 2018 3:26:51 PM by Hibernate Tools 4.3.1



/**
 * Dokument generated by hbm2java
 */
public class Dokument  implements java.io.Serializable {


     private Integer iddokument;
     private Projekat projekat;
     private String naziv;
     private String opis;
     private byte[] dokument;
     private String ekstenzija;

    public Dokument() {
    }

	
    public Dokument(Projekat projekat, String naziv, byte[] dokument, String ekstenzija) {
        this.projekat = projekat;
        this.naziv = naziv;
        this.dokument = dokument;
        this.ekstenzija = ekstenzija;
    }
    public Dokument(Projekat projekat, String naziv, String opis, byte[] dokument, String ekstenzija) {
       this.projekat = projekat;
       this.naziv = naziv;
       this.opis = opis;
       this.dokument = dokument;
       this.ekstenzija = ekstenzija;
    }
   
    public Integer getIddokument() {
        return this.iddokument;
    }
    
    public void setIddokument(Integer iddokument) {
        this.iddokument = iddokument;
    }
    public Projekat getProjekat() {
        return this.projekat;
    }
    
    public void setProjekat(Projekat projekat) {
        this.projekat = projekat;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public byte[] getDokument() {
        return this.dokument;
    }
    
    public void setDokument(byte[] dokument) {
        this.dokument = dokument;
    }
    public String getEkstenzija() {
        return this.ekstenzija;
    }
    
    public void setEkstenzija(String ekstenzija) {
        this.ekstenzija = ekstenzija;
    }




}


