package prijava.beans;
// Generated Jul 8, 2018 12:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grad generated by hbm2java
 */
public class Grad  implements java.io.Serializable {


     private Integer idgrad;
     private String naziv;
     private Set prijavas = new HashSet(0);

    public Grad() {
    }

	
    public Grad(String naziv) {
        this.naziv = naziv;
    }
    public Grad(String naziv, Set prijavas) {
       this.naziv = naziv;
       this.prijavas = prijavas;
    }
   
    public Integer getIdgrad() {
        return this.idgrad;
    }
    
    public void setIdgrad(Integer idgrad) {
        this.idgrad = idgrad;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getPrijavas() {
        return this.prijavas;
    }
    
    public void setPrijavas(Set prijavas) {
        this.prijavas = prijavas;
    }

@Override
    public String toString() {
        return naziv;
    }


}


