package prijava.beans;
// Generated Feb 13, 2018 3:26:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prijava generated by hbm2java
 */
public class Prijava  implements java.io.Serializable {


     private Integer idprijava;
     private Grad grad;
     private String nazivtima;
     private String napomena;
     private String username;
     private String password;
     private String uloga;
     private byte uslovi;
     private Set clans = new HashSet(0);
     private Set projekats = new HashSet(0);

    public Prijava() {
    }

	
    public Prijava(String nazivtima, String username, String password, String uloga) {
        this.nazivtima = nazivtima;
        this.username = username;
        this.password = password;
        this.uloga = uloga;
    }
    public Prijava(Grad grad, String nazivtima, String napomena, String username, String password, String uloga, Set clans, Set projekats) {
       this.grad = grad;
       this.nazivtima = nazivtima;
       this.napomena = napomena;
       this.username = username;
       this.password = password;
       this.uloga = uloga;
       this.clans = clans;
       this.projekats = projekats;
    }
   
    public Integer getIdprijava() {
        return this.idprijava;
    }
    
    public void setIdprijava(Integer idprijava) {
        this.idprijava = idprijava;
    }
    public Grad getGrad() {
        return this.grad;
    }
    
    public void setGrad(Grad grad) {
        this.grad = grad;
    }
    public String getNazivtima() {
        return this.nazivtima;
    }
    
    public void setNazivtima(String nazivtima) {
        this.nazivtima = nazivtima;
    }
    public String getNapomena() {
        return this.napomena;
    }
    
    public void setNapomena(String napomena) {
        this.napomena = napomena;
    }
    public String getUsername() {
        return this.username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUloga() {
        return this.uloga;
    }
    public void setUloga(String uloga) {
        this.uloga = uloga;
    }
    public byte getUslovi() {
        return uslovi;
    }
    public void setUslovi(byte uslovi) {
        this.uslovi = uslovi;
    }
    public Set getClans() {
        return this.clans;
    }
    public void setClans(Set clans) {
        this.clans = clans;
    }
    public Set getProjekats() {
        return this.projekats;
    }
    
    public void setProjekats(Set projekats) {
        this.projekats = projekats;
    }




}


